# fly.toml app configuration file generated for pbn
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pbn'
primary_region = 'sea'

[build]

[deploy]
  strategy = "bluegreen"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 2
  processes = ['app']

[[http_service.checks]]
  interval = "10s"
  timeout = "5s"
  grace_period = "10s"  # Ensure this is sufficient for your app to start
  method = "GET"
  path = "/healthz"  # Verify this endpoint returns HTTP 200 when healthy

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1